# Configuration file for training parameters

# 시스템 파라미터
device: 'cuda:0'

# 데이터 파라미터
data_dir: './'
train_file:
  - 's_train.npy'
  - 'e_train.npy'
val_file:
  - 's_val.npy'
  - 'e_val.npy'

# 학습 파라미터
use_seg_loss: true
k: [1.0, 1.0, 1.0]
norm: 'L2'
normalization: null

# 트레이너 파라미터
batch_size: 100
epochs: 600
optimizer: 'adam'
learning_rate: 0.0001 